# Generated by Django 5.2.1 on 2025-06-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_first_name_accounts_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
